server:
  port: 8851

spring:
  application:
    name: springcloud-consumer
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 106.12.174.147:8848
        enabled: true
#        instance-enabled: true

# sentinel 相关配置
    sentinel:
      eager: true # 取消Sentinel控制台懒加载
      transport:
        dashboard: localhost:8080

# 要公开的端点列表
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# feign相关配置
feign:
  circuitbreaker:
    enabled: true  # 开启熔断，开启之后 feign的fallback机制才会生效
  sentinel:
    enabled: true # 开启feign对sentinel的支持