server:
  port: 8849

spring:
  application:
    name: springcloud-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 106.12.174.147:8848
        enabled: true

    gateway:
      routes:
      - id: springcloud-provider
        uri: http://localhost:8850/
        predicates[0]:
          name: Path
          args[pattern]: /echo-api/**
        filters:
        - StripPrefix=1

      - id: springcloud-authorization
        uri: http://localhost:8852/
        predicates[0]:
          name: Path
          args[pattern]: /auth-api/**
        filters:
          - StripPrefix=1

# 要公开的端点列表
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
#  config: /springcloud-gateway/logback.xml
  level:
    com.benny: info